name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Ändra till rätt version

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Debug target directory
        run: ls -l target

  #build-docker:
   # runs-on: ubuntu-latest
    #needs: test

    #steps:
     # - name: Check out code
      #  uses: actions/checkout@v3

      #- name: Log in to DockerHub
       # run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      #- name: Build Docker Image
       # run: docker build --build-arg JAR_FILE=target/Java_Enterprise_School_Projekt-0.0.1-SNAPSHOT.jar -t roleonce/java_enterprise_school_projekt:latest .

      #- name: Push Docker Image
       # run: docker push roleonce/java_enterprise_school_projekt:latest
